name: Auto Update IPTV Playlist

on:
  schedule:
    - cron: '0 */6 * * *' # প্রতি ৬ ঘণ্টা পর পর আপডেট হবে
  workflow_dispatch: # ম্যানুয়ালি রান করার জন্য

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Python Script
        run: python main.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add playlist.m3u
          git commit -m "Auto updated playlist" || exit 0
          git push
