name: Auto Update IPTV Playlist

on:
  schedule:
    - cron: '*/5 * * * *' # প্রতি ৫ মিনিট পর পর চেক করবে
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Python Script
        run: python main.py

      - name: Check for changes and Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add playlist.m3u
          # যদি ফাইলে কোনো পরিবর্তন হয়, তবেই গিটহাবে পুশ করবে
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto updated playlist with new tokens" && git push)
